<?php

namespace TransfertBundle\Repository;

/**
 * TransfertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransfertRepository extends \Doctrine\ORM\EntityRepository
{
}
